
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIASSB2BYCSG3PWJXXJ
      secret-key: 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
    end-point-sqs:
      uri: https://sqs.us-east-1.amazonaws.com/176215408804/fila001
    end-point-sns:
      uri: arn:aws:sns:us-east-1:176215408804:topic001
    end-point-s3:
      uri: meu-bucket-001



spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB