
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key:
      secret-key:
    end-point-sqs:
      uri:
    end-point-sns:
      uri:
    end-point-s3:
      uri:



spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB